name: MLOps AQI Pipeline

on:
  schedule:
    # Run feature pipeline every hour
    - cron: '0 * * * *'
    # Run training pipeline every Sunday at 2 AM
    - cron: '0 2 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 * * * *' || github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run feature pipeline
      env:
        WAQI_API_KEY: ${{ secrets.WAQI_API_KEY }}
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        python src/feature_pipeline.py

  training_pipeline:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 2 * * 0' || github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run training pipeline
      env:
        WAQI_API_KEY: ${{ secrets.WAQI_API_KEY }}
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        python src/training_pipeline.py
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-models
        path: models/